# Generated by Django 5.2.8 on 2025-11-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ram', 'RAM'), ('motherboard', 'Motherboard'), ('cpu', 'CPU'), ('gpu', 'GPU'), ('storage', 'Storage'), ('psu', 'Power Supply'), ('case', 'Case')], default='ram', max_length=50),
        ),
    ]
