# Generated by Django 5.2.8 on 2026-01-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_pcbuild_pcbuilditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcbuilditem',
            old_name='pc_build',
            new_name='build',
        ),
        migrations.AddField(
            model_name='pcbuilditem',
            name='price_at_time',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pcbuilditem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
