# Generated by Django 5.2.8 on 2026-02-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('forgot_password', 'Forgot Password'), ('delete_build', 'Delete Build')], max_length=50),
        ),
    ]
